import { Product, SortConfig } from './types/product';

export const allProducts: Product[] = [
  // Ingredients Category
  {
    id: 1,
    name: "Dark Compound Chocolate",
    description: "Premium quality dark compound chocolate, perfect for coating, molding, and decorating. Contains 55% cocoa content.",
    price: 280,
    unit: "kg",
    category: "Ingredients",
    subcategory: "Chocolate",
    badge: "Bestseller",
    image: "chocolate.jpg",
    rating: 4.8,
    reviews: 156,
    inStock: true,
    minOrder: 1,
    tags: ["chocolate", "baking", "coating", "premium"]
  },
  {
    id: 2,
    name: "Premium Whipping Cream",
    description: "High-fat whipping cream (35% fat) for perfect peaks every time. Ideal for cakes, pastries, and desserts.",
    price: 320,
    unit: "ltr",
    category: "Dairy & Fats",
    subcategory: "Cream",
    badge: "In Stock",
    image: "cream.jpg",
    rating: 4.9,
    reviews: 243,
    inStock: true,
    minOrder: 2,
    tags: ["cream", "dairy", "whipping", "premium"]
  },
  {
    id: 3,
    name: "Cake Base Boards (10-inch)",
    description: "Food-grade silver cake boards, sturdy and grease-resistant. Perfect for professional cake presentation.",
    price: 15,
    unit: "piece",
    category: "Packaging",
    subcategory: "Boards",
    badge: "New",
    image: "boards.jpg",
    rating: 4.6,
    reviews: 89,
    inStock: true,
    minOrder: 10,
    tags: ["packaging", "cake", "boards", "silver"]
  },
  {
    id: 4,
    name: "Premium Bread Flour",
    description: "High-protein bread flour (13% protein) for perfect bread texture. Imported wheat, stone-ground.",
    price: 45,
    unit: "kg",
    category: "Ingredients",
    subcategory: "Flour",
    badge: "Bestseller",
    image: "flour.jpg",
    rating: 4.9,
    reviews: 312,
    inStock: true,
    minOrder: 5,
    tags: ["flour", "bread", "protein", "baking"]
  },
  {
    id: 5,
    name: "Vanilla Extract Essence",
    description: "Pure Madagascar vanilla extract. Natural, alcohol-based, intense flavor for all baking needs.",
    price: 180,
    unit: "bottle",
    category: "Flavors & Additives",
    subcategory: "Extracts",
    badge: "Premium",
    image: "vanilla.jpg",
    rating: 5.0,
    reviews: 198,
    inStock: true,
    minOrder: 1,
    discount: 10,
    tags: ["vanilla", "extract", "flavor", "premium", "natural"]
  },
  {
    id: 6,
    name: "Butter Cookies Mix",
    description: "Ready-to-use butter cookies mix. Just add water and bake. Makes 50+ cookies per pack.",
    price: 95,
    unit: "kg",
    category: "Ready Mixes",
    subcategory: "Cookie Mix",
    badge: "New",
    image: "mix.jpg",
    rating: 4.5,
    reviews: 67,
    inStock: true,
    minOrder: 2,
    tags: ["cookies", "mix", "ready-made", "easy"]
  },
  {
    id: 7,
    name: "Professional Piping Bags (100pcs)",
    description: "Disposable piping bags, 12-inch, food-grade plastic. Strong and tear-resistant.",
    price: 120,
    unit: "pack",
    category: "Baking Tools",
    subcategory: "Piping",
    badge: "In Stock",
    image: "piping.jpg",
    rating: 4.7,
    reviews: 134,
    inStock: true,
    minOrder: 1,
    tags: ["piping", "decorating", "disposable", "tools"]
  },
  {
    id: 8,
    name: "Edible Gold Dust",
    description: "Luxury edible gold dust for cake decoration. Non-toxic, food-safe shimmer powder.",
    price: 450,
    unit: "jar",
    category: "Decorations",
    subcategory: "Shimmer",
    badge: "Premium",
    image: "gold-dust.jpg",
    rating: 4.8,
    reviews: 92,
    inStock: true,
    minOrder: 1,
    tags: ["gold", "decoration", "shimmer", "luxury", "premium"]
  },
  {
    id: 9,
    name: "White Compound Chocolate",
    description: "Creamy white compound chocolate for coating and molding. Smooth texture and easy to work with.",
    price: 290,
    unit: "kg",
    category: "Ingredients",
    subcategory: "Chocolate",
    badge: "Bestseller",
    image: "chocolate.jpg",
    rating: 4.7,
    reviews: 178,
    inStock: true,
    minOrder: 1,
    tags: ["chocolate", "white", "coating", "baking"]
  },
  {
    id: 10,
    name: "Almond Flour (Blanched)",
    description: "Finely ground blanched almond flour. Perfect for gluten-free and keto baking.",
    price: 380,
    unit: "kg",
    category: "Ingredients",
    subcategory: "Flour",
    badge: "Premium",
    image: "flour.jpg",
    rating: 4.9,
    reviews: 145,
    inStock: true,
    minOrder: 1,
    discount: 15,
    tags: ["almond", "flour", "gluten-free", "keto", "premium"]
  },
  {
    id: 11,
    name: "Buttercream Frosting Mix",
    description: "Instant buttercream frosting mix. Just add butter and whip. Available in multiple flavors.",
    price: 125,
    unit: "kg",
    category: "Ready Mixes",
    subcategory: "Frosting",
    badge: "New",
    image: "mix.jpg",
    rating: 4.6,
    reviews: 88,
    inStock: true,
    minOrder: 2,
    tags: ["frosting", "buttercream", "mix", "ready-made"]
  },
  {
    id: 12,
    name: "Cake Boxes (8x8 inch)",
    description: "White cake boxes with window. Eco-friendly cardboard, grease-resistant coating.",
    price: 25,
    unit: "piece",
    category: "Packaging",
    subcategory: "Boxes",
    badge: "In Stock",
    image: "boards.jpg",
    rating: 4.5,
    reviews: 76,
    inStock: true,
    minOrder: 20,
    tags: ["packaging", "boxes", "cake", "window", "eco-friendly"]
  },
  {
    id: 13,
    name: "Strawberry Emulsion",
    description: "Natural strawberry emulsion for baking. Water-based, heat-stable flavor.",
    price: 145,
    unit: "bottle",
    category: "Flavors & Additives",
    subcategory: "Emulsions",
    badge: "In Stock",
    image: "vanilla.jpg",
    rating: 4.4,
    reviews: 63,
    inStock: true,
    minOrder: 1,
    tags: ["strawberry", "emulsion", "flavor", "natural"]
  },
  {
    id: 14,
    name: "Sprinkles Mix (Rainbow)",
    description: "Colorful rainbow sprinkles mix. Food-safe colors, perfect for cakes and cupcakes.",
    price: 85,
    unit: "jar",
    category: "Decorations",
    subcategory: "Sprinkles",
    badge: "Bestseller",
    image: "gold-dust.jpg",
    rating: 4.7,
    reviews: 201,
    inStock: true,
    minOrder: 2,
    tags: ["sprinkles", "rainbow", "decoration", "colorful"]
  },
  {
    id: 15,
    name: "Stainless Steel Spatula Set",
    description: "Professional 3-piece spatula set. Heat-resistant, dishwasher safe.",
    price: 195,
    unit: "set",
    category: "Baking Tools",
    subcategory: "Spatulas",
    badge: "Premium",
    image: "piping.jpg",
    rating: 4.8,
    reviews: 112,
    inStock: true,
    minOrder: 1,
    tags: ["spatula", "tools", "stainless", "professional"]
  },
  {
    id: 16,
    name: "Unsalted Butter (Restaurant Quality)",
    description: "Premium unsalted butter, 82% fat content. Perfect for baking and pastry work.",
    price: 420,
    unit: "kg",
    category: "Dairy & Fats",
    subcategory: "Butter",
    badge: "Premium",
    image: "cream.jpg",
    rating: 5.0,
    reviews: 267,
    inStock: true,
    minOrder: 2,
    tags: ["butter", "dairy", "unsalted", "premium", "baking"]
  },
  {
    id: 17,
    name: "Cocoa Powder (Dutch Process)",
    description: "Alkalized Dutch cocoa powder. Rich, dark color and smooth flavor.",
    price: 185,
    unit: "kg",
    category: "Ingredients",
    subcategory: "Cocoa",
    badge: "Bestseller",
    image: "chocolate.jpg",
    rating: 4.9,
    reviews: 189,
    inStock: true,
    minOrder: 1,
    tags: ["cocoa", "powder", "dutch", "chocolate", "baking"]
  },
  {
    id: 18,
    name: "Fondant (Ready to Roll)",
    description: "Pre-made fondant in various colors. Smooth, pliable, and easy to work with.",
    price: 165,
    unit: "kg",
    category: "Decorations",
    subcategory: "Fondant",
    badge: "In Stock",
    image: "gold-dust.jpg",
    rating: 4.6,
    reviews: 98,
    inStock: true,
    minOrder: 1,
    tags: ["fondant", "decoration", "ready-made", "cake"]
  },
  {
    id: 19,
    name: "Cupcake Liners (Premium)",
    description: "Grease-proof cupcake liners. Available in multiple colors and patterns.",
    price: 45,
    unit: "pack",
    category: "Packaging",
    subcategory: "Liners",
    badge: "New",
    image: "boards.jpg",
    rating: 4.5,
    reviews: 54,
    inStock: true,
    minOrder: 5,
    tags: ["cupcake", "liners", "packaging", "grease-proof"]
  },
  {
    id: 20,
    name: "Cream Cheese (Bakery Grade)",
    description: "Professional cream cheese for frosting and cheesecakes. High fat content.",
    price: 340,
    unit: "kg",
    category: "Dairy & Fats",
    subcategory: "Cheese",
    badge: "Bestseller",
    image: "cream.jpg",
    rating: 4.9,
    reviews: 223,
    inStock: true,
    minOrder: 2,
    tags: ["cream cheese", "dairy", "frosting", "cheesecake", "bakery"]
  },
];

export const sortOptions: SortConfig[] = [
  { value: 'popular', label: 'Most Popular' },
  { value: 'newest', label: 'Newest First' },
  { value: 'price-low', label: 'Price: Low to High' },
  { value: 'price-high', label: 'Price: High to Low' },
  { value: 'rating', label: 'Highest Rated' },
  { value: 'name-az', label: 'Name: A to Z' },
  { value: 'name-za', label: 'Name: Z to A' },
];

export const categories = [
  { id: 'all', name: 'All Products', count: 20 },
  { id: 'ingredients', name: 'Ingredients', count: 6 },
  { id: 'dairy-fats', name: 'Dairy & Fats', count: 3 },
  { id: 'packaging', name: 'Packaging', count: 3 },
  { id: 'flavors', name: 'Flavors & Additives', count: 2 },
  { id: 'decorations', name: 'Decorations', count: 3 },
  { id: 'ready-mixes', name: 'Ready Mixes', count: 2 },
  { id: 'baking-tools', name: 'Baking Tools', count: 2 },
];

export const priceRanges = [
  { id: 'all', label: 'All Prices', min: 0, max: Infinity },
  { id: 'under-100', label: 'Under ₹100', min: 0, max: 100 },
  { id: '100-200', label: '₹100 - ₹200', min: 100, max: 200 },
  { id: '200-300', label: '₹200 - ₹300', min: 200, max: 300 },
  { id: '300-400', label: '₹300 - ₹400', min: 300, max: 400 },
  { id: 'above-400', label: 'Above ₹400', min: 400, max: Infinity },
];